// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dnormpar2
NumericVector dnormpar2(NumericVector x, NumericVector mu, NumericVector sig);
RcppExport SEXP _dnormpar2_dnormpar2(SEXP xSEXP, SEXP muSEXP, SEXP sigSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sig(sigSEXP);
    rcpp_result_gen = Rcpp::wrap(dnormpar2(x, mu, sig));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _dnormpar2_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dnormpar2_dnormpar2", (DL_FUNC) &_dnormpar2_dnormpar2, 3},
    {"_dnormpar2_rcpp_hello_world", (DL_FUNC) &_dnormpar2_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_dnormpar2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
