# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dnormpar2 <- function(x, mu, sig) {
    .Call(`_dnormpar2_dnormpar2`, x, mu, sig)
}

rcpp_hello_world <- function() {
    .Call(`_dnormpar2_rcpp_hello_world`)
}

